apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  volumes:
    - name: shared-volumes
      emptyDir: {}
  containers:
    - name: nginx-containers
      image: nginx
      ports:
        - name: http
          containerPorts: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: shared-volumes
    - name: debian-container
      image: debian
      volumeMounts:
        - name: shared-volumes
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container > /pod-data/index.html; sleep 1000"]
